name: 'E-Renew'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '55 5 10,12,14,16,18,20,22 * ?'

jobs:
  AUTO_RENEW:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2

      - name: 'Setup Python'
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'

      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade requests
          python -m pip install --upgrade beautifulsoup4

      - name: 'Auto Renew'
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          TOKEN: ${{ secrets.TOKEN }}
        run: python main.py
